# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
# `npm install` (not `npm ci`) so the build tolerates lock/npm-version differences — the lock is
# generated by npm 11 (local) but node:20-alpine ships npm 10, which reads npm 11's optional
# platform deps (@esbuild/linux-*) as "missing" and fails `npm ci`. install regenerates as needed.
RUN npm install --no-audit --no-fund
COPY . .
ENV NODE_OPTIONS="--max-old-space-size=2560"
RUN npm run build

# Production stage — Nginx with envsubst for BACKEND_URL
FROM nginx:alpine

# Copy built SPA
COPY --from=build /app/dist /usr/share/nginx/html

# Copy Nginx config template (uses $BACKEND_URL variable)
COPY nginx.conf /etc/nginx/templates/default.conf.template

EXPOSE 80

# nginx:alpine supports /etc/nginx/templates/*.template
# It auto-runs envsubst on them at startup, outputting to /etc/nginx/conf.d/
# BACKEND_URL must be set as an environment variable
CMD ["nginx", "-g", "daemon off;"]
